### ISSUE TITLE
Error when Building

### ISSUE THREAD

**Issue by adamchang2000** [1justin-code/Musicalnsight#1]
Hi,

I ran into this error when building this project. Any tips?
![image](https://user-images.githubusercontent.com/44257083/173154941-7d111cc3-ebc3-41a9-a4cc-cd25fd2a004f.png)

**Comment by 1justin-code** [comment]
Hey adam! Can you send me the entire error code so I can see the problem?

**Comment by 1justin-code** [comment]
fixed!
